AUTHENTICATION_TYPE: Database
BITTORRENT_FILENAME_PEPPER: bc0fee9a-abf2-4caf-9ea9-1dc03ca93f11
BUILDLOGS_REDIS: {host: 172.30.176.184, password: quayredis, port: 6379}
DB_URI: postgresql://quayuser:quaypass@172.30.176.190:5432/quaydb
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - SwiftStorage
  - auth_url: 
    auth_version: '2'
    os_options: {tenant_id: }
    storage_path: /datastorage/registry
    swift_container: quay
    swift_password: 
    swift_user: 
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE: [default]
ENTERPRISE_LOGO_URL: /static/img/quay-logo.png
FEATURE_ACI_CONVERSION: false
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: true
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BUILD_SUPPORT: true
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_GITHUB_LOGIN: true
FEATURE_GOOGLE_LOGIN: true
FEATURE_MAILING: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_SECURITY_SCANNER: true
FEATURE_USER_CREATION: true
FEATURE_USER_LOG_ACCESS: true
GITHUB_LOGIN_CONFIG: {API_ENDPOINT: 'https://api.github.com/', CLIENT_ID: ,
  CLIENT_SECRET: , GITHUB_ENDPOINT: 'https://github.com/'}
GOOGLE_LOGIN_CONFIG: {CLIENT_ID: ,
  CLIENT_SECRET: }
GITHUB_TRIGGER_CONFIG: {}
GITLAB_TRIGGER_KIND: {}
GPG2_PRIVATE_KEY_FILENAME: signing-private.gpg
GPG2_PUBLIC_KEY_FILENAME: signing-public.gpg
LOG_ARCHIVE_LOCATION: default
MAIL_DEFAULT_SENDER: support@quay.io
MAIL_PORT: 587
MAIL_USE_TLS: true
PREFERRED_URL_SCHEME: https
SECRET_KEY: 
SECURITY_SCANNER_ENDPOINT: http://172.30.30.216:6060
SECURITY_SCANNER_ISSUER_NAME: security_scanner
SERVER_HOSTNAME: 
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
SUPER_USERS: [root]
TAG_EXPIRATION_OPTIONS: [0s, 1d, 1w, 2w, 4w]
TEAM_RESYNC_STALE_TIME: 60m
TESTING: true
USERFILES_LOCATION: default
USERFILES_PATH: userfiles/
USER_EVENTS_REDIS: {host: 172.30.176.184, password: quayredis, port: 6379}
USE_CDN: false
