apiVersion: v1
kind: Service
metadata:
  namespace: quay-enterprise
  name: quay-config-tool
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: web
  selector:
    quay-enterprise-component: config-tool
