apiVersion: v1
kind: Service
metadata:
  namespace: quay-enterprise
  name: quay-config-tool-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30090
  selector:
    quay-enterprise-component: config-tool
